server:
  port: 8080

spring:
  application:
    name: Online Shop Web
  datasource:
    url: jdbc:mysql://localhost:3306/online_store
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mail:
    host: smtp.gmail.com
    port: 587
    username: murazyan.tamara5566@gmail.com
    password: hosj dsda nqwz liau
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true