server:
  port: 8081
spring:


  datasource:
    url: jdbc:mysql://localhost:3306/online_store
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: murazyan.tamara5566@gmail.com
    password: hosj dsda nqwz liau
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


  liquibase:
    change-log: classpath:/db/changelog.xml

online-store:
  jwt:
    secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0
    expiration: 99999999